export default {
    NEW_MESSAGE_ADDED: 'NEW_MESSAGE_ADDED',
    MESSAGES_POLL_RESULT: 'MESSAGES_POLL_RESULT',
    CHANNEL_POLL_RESULT: 'CHANNEL_POLL_RESULT',
    NEW_MESSAGE_ADD_COMPLETED: 'NEW_MESSAGE_ADD_COMPLETED',
};
